version: '3.8'
services:
  vehicle-service:
    container_name: vehicle-service
    image: vehicle-service
    build: ./
    ports:
      - "8004:8004"
    depends_on:
      - vehicle-db
  vehicle-db:
    container_name: vehicle-db
    image: postgres
    ports:
      - "7004:7004"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=vehicle-db
      - PGPORT=7004
networks:
  default:
    external: true
    name: pds_network
